---
language: java
jdk: openjdk11
dist: focal

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

before_cache: rm -rf $HOME/.m2/repository/org/alfresco/alfresco-file-transfer-receiver

branches:
  only:
    - master
    - /release\/.*/
    - /support\/.*/
    - /feature\/.*/

stages:
  - name: tests
    if: commit_message !~ /\[skip tests\]/
  - name: release
    if: commit_message =~ /\[release\]/ AND branch ~= /^(master|support\/.+|release\/.+|feature\/.+)$/ AND type != pull_request AND fork = false
  - name: publish
    if: commit_message =~ /\[publish\]/ AND branch ~= /^(master|support\/.+|release\/.+|feature\/.+)$/ AND type != pull_request AND fork = false

before_install: mkdir -p ${HOME}/.m2 && cp -rf _ci/settings.xml ${HOME}/.m2/

jobs:
  include:
    - name: "Unit Tests"
      stage: tests
      script: mvn -B -U install

    - name: "Release and Copy to S3 Staging Bucket"
      stage: release
      script: travis_wait 60 bash _ci/maven_release.sh
      before_deploy:
        - mkdir -p deploy_dir
        - ARTIFACT=$(find . -name "alfresco-file-transfer-receiver-*.zip" -printf "%f\n" | head -1)
        - export VERSION=$(echo "${ARTIFACT}" | sed -e "s/^alfresco-file-transfer-receiver-//" -e "s/\.zip$//")
        - ln "alfresco-ftr-distribution/target/${ARTIFACT}" "deploy_dir/${ARTIFACT}"
        - echo "Local deploy_dir content:"
        - ls -lA deploy_dir
      deploy:
        - provider: s3
          access_key_id: ${AWS_STAGING_ACCESS_KEY}
          secret_access_key: ${AWS_STAGING_SECRET_KEY}
          region: "eu-west-1"
          bucket: "alfresco-artefacts-staging"
          upload_dir: "alfresco-file-transfer-receiver/release/${VERSION}"
          skip_cleanup: true
          local_dir: "deploy_dir"
          on:
            all_branches: true
      after_deploy: echo "Finished release and deployed to https://s3.console.aws.amazon.com/s3/buckets/alfresco-artefacts-staging/alfresco-file-transfer-receiver/release/${VERSION}"

    - name: "Copy to S3 Release Bucket"
      stage: publish
      install: skip
      script: skip
      before_deploy: pip install awscli
      deploy:
        - provider: script
          script: sh _ci/copy_to_release_bucket.sh
          skip_cleanup: true
          on:
            all_branches: true